### PR TITLE
XMPP Providers - Curated List of Providers for Registration and Autocomplete

### LINKED ISSUE #158: Onboarding: Use curated list of XMPP Providers
Hello,

Here is my suggestion to make use of the curated server list from the [XMPP Providers project](https://invent.kde.org/melvo/xmpp-providers). Transparency: Yes it is another project where I am involved in.

The advantage is that it can simply ready via JSON and, that's what I highly recommend, can make use of guiding users directly to the right support address if they have one of those domain. It can also offer many other options, as randomized distribution of user but also allocation based on e.g. users choice by country / suggestions based on IP / device language. We can also automatically register the user to the relevant support chat / or admin JID.

If you clone the repository and run the script you get three categories. Category A has the best ranking and also only list servers which support IBR (in-band registration). The output lists only list the servers an no details, but if it is of interest to make use of some details, those need to be exported as well. Bear in mind that the C lists might have servers with bad properties of any kind. So I do not recommend to take the bare list.

Also happy to hear your feedback to the project. Let me know if there are technical questions.

### PR DESCRIPTION
**Pull request by COM8**
Adds support for [XMPP Providers](https://invent.kde.org/melvo/xmpp-providers/-/tree/master) for auto complete and registration.
Closes #158
currated_server_list

### CODE REVIEW

**Comment by Echolon** [comment]
This is work by someone with serious intensions. I'm in love! ❤️ 

Just do me a favor and remove draugr.de and blabber.im for the moment

**Comment by melvo** [comment]
@COM8 This is really great!

**Comment by melvo** [comment]
@COM8 here are some minor issues :)
1. I suggest to use the term *provider* instead of *server* because many people are already familiar with the term email provider.
1. There is a misspelling: *XMPP server provides* instead of *XMPP server provide**r**s*.
1. The current list contains all providers (category C). We created the categories A and B for the purpose of registration. Maybe you could use `./filter.py -B` for automatically generating a list of providers that are good enough for creating an account. In addition, that would be better for updating the list in the future because you do not have to adjust it manually. All changes in the XMPP Providers project will directly affect the filtered list generated by the filter script.

**Comment by COM8** [comment]
> 
> 
> @COM8 here are some minor issues :)
> 
>     1. I suggest to use the term _provider_ instead of _server_ because many people are already familiar with the term email provider.
> 

ACK. Sounds reasonable.


>     2. There is a misspelling: _XMPP server provides_ instead of _XMPP server provide**r**s_.

Thanks.

> 
>     3. The current list contains all providers (category C). We created the categories A and B for the purpose of registration. Maybe you could use `./filter.py -B` for automatically generating a list of providers that are good enough for creating an account. In addition, that would be better for updating the list in the future because you do not have to adjust it manually. All changes in the XMPP Providers project will directly affect the filtered list generated by the filter script.

Currently I'm using all lists until I have a way to retrieve them from some kind of online source.
https://github.com/UWPX/UWPX-Client/tree/master/UWPX_UI/Resources/Providers
https://github.com/UWPX/UWPX-Client/blob/master/UWPX_UI/Resources/Providers/generate.ps1
For registration I switched from the C-list to the B-list.

**Comment by Neustradamus** [comment]
@COM8: Nice!

**Comment by melvo** [comment]
@COM8 The filtered provider lists for all categories will be [provided by xmpp.net](https://github.com/xsf/infrastructure/issues/14). You will then be able to simply download them.

**Comment by COM8** [comment]
> @COM8 The filtered provider lists for all categories will be [provided by xmpp.net](https://github.com/xsf/infrastructure/issues/14). You will then be able to simply download them.

Awesome!

**Comment by COM8** [comment]
Thanks for the update! I will update my scripts.

**Pull request merged**
