### PR TITLE
Changed variables within Consts.cs

### PR DESCRIPTION
**Pull request by iilegacyyii**
Changed variables within const.cs to const to help reduce human error in future development.

### CODE REVIEW

**Comment by COM8** [comment]
@iilegacyyii thanks for contributing.
Is this PR intended to be empty?

**Comment by iilegacyyii** [comment]
frog
yes

**Comment by iilegacyyii** [comment]
If I ask really nicely can you please merge this? I would like to keep the frog in commit history

**Comment by COM8** [comment]
First of all, I can not find any "frog" inside your two commits.
Secondly, do you have the copyright for your "frog"?

**Pull request closed without merging**
